name: build-release

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ARM toolchain
        run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build firmware
        id: build
        run: |
          mkdir -p cmake-build-release
          cd cmake-build-release
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
          make
